### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by NebN** [rale/lgtv#1]
I have installed the custom integration, but I am unsure how to set it up. 
Would it be possible to update the repo with a quick readme on the steps to follow?

**Comment by rale** [comment]
Sure, I updated the readme with installation steps.  Let me know if it's still not clear.

**Comment by NebN** [comment]
Worked, thanks.
Now I'm realizing I'm unsure how to test it, could you possibly add additional instructions? It's not working "out of the box" on an LG CX if that is what this fork does.
I read [here](https://github.com/home-assistant/core/issues/91709) about the various endpoints, but I am unsure how to call them.

**Comment by rale** [comment]
If it's working, you should just see the state of the device change to playing whenever you have something playing in a media player app (the built in media player, youtube, netflix, etc).

That said, I know it doesn't work on some older TVs, and can only say for sure that it works on 2022 models at least.
